### ISSUE TITLE
Download / Export Data Sets

### ISSUE THREAD

**Issue by cernst122** [Spelman-College/spelman-dashboard#16]
- [ ] Requirement 1: Upon viewing the data, the user sees available download options for file type (e.g. CSV, Excel, JSON)
- [ ] Requirement 2: User can choose only one file type option (at a time)
- [ ] Requirement 3: User clicks button to download
- [ ] Requirement 4: Visual response is provided, confirming download attempt

**Comment by cernst122** [comment]
Backend prototype should either fetch proper URL for user to download data on DC site, or natively parse DC API call results to CSV (see internal TDD for details).

**Comment by mattsmithtaiko** [comment]
Data Commons' Data Download Tool doesn't expose the direct link to the `.csv` file. We can link to the Data Download tool pretty easily since all the parameters are exposed in the url (example: `https://datacommons.org/tools/download#pt=City&place=geoId%2F13&sv=Count_Person_BachelorOfScienceAndEngineeringRelatedMajor&dtType=LATEST&facets=%7B%7D`).

I did find one undocumented way to download data by making an unauthenticated POST request to https://datacommons.org/api/within. To download the csv of the data linked above, we can POST this data:

```json
{
  "parentPlace": "geoId/13",
  "childType": "City",
  "statVars": [
    "Count_Person_BachelorOfScienceAndEngineeringRelatedMajor"
  ],
  "facetMap": {
    "Count_Person_BachelorOfScienceAndEngineeringRelatedMajor": ""
  },
  "minDate": "latest",
  "maxDate": "latest"
}
```

Considering this is a hidden unauthenticated endpoint, we'd want to check with the DC team to make sure it's ok to use this endpoint and to make sure we won't be adding an undue traffic load.
